# Generated by Django 5.0.6 on 2024-10-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('usn', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
